# Generated by Django 5.2 on 2025-04-09 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Trials",
            fields=[
                ("trial_id", models.AutoField(primary_key=True, serialize=False)),
                ("trial_name", models.CharField(max_length=100)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
            ],
            options={
                "db_table": "trials",
            },
        ),
    ]
