# Generated by Django 5.2 on 2025-04-11 19:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("prilozenie1", "0002_trials_med"),
    ]

    operations = [
        migrations.CreateModel(
            name="Patients",
            fields=[
                ("patient_id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100)),
                ("age", models.IntegerField()),
                ("gender", models.CharField(max_length=10)),
                ("conditions", models.CharField(max_length=100)),
            ],
            options={
                "db_table": "patients",
            },
        ),
        migrations.CreateModel(
            name="Measurements",
            fields=[
                ("measurement_id", models.AutoField(primary_key=True, serialize=False)),
                ("measurement_date", models.DateField(auto_now_add=True)),
                ("drug", models.CharField(max_length=100)),
                ("condition_score", models.IntegerField()),
                (
                    "trial_id",
                    models.ForeignKey(
                        db_column="trial_id",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="prilozenie1.trials",
                    ),
                ),
                (
                    "patient_id",
                    models.ForeignKey(
                        db_column="patient_id",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="prilozenie1.patients",
                    ),
                ),
            ],
            options={
                "db_table": "measurements",
            },
        ),
    ]
