# Generated by Django 5.2 on 2025-04-09 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("prilozenie1", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="trials",
            name="med",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
